manifest:
  remotes:
    - name: zephyr-andriyhrabchak
      url-base: https://github.com/andriyhrabchak
  projects:
    - name: zephyr
      remote: zephyr-andriyhrabchak
      revision: initialize_ref_clk_in_mdio_esp32
      import: 
        name-allowlist:
          - hal_espressif
          - littlefs
          - fatfs
          - mcuboot
          - mbedtls
          - zcbor
  self:
    path: app
